[package]
name = "rbxlx-to-rojo"
version = "1.0.1"
authors = ["Kampfkarren"]
edition = "2018"

[lib]
name = "rbxlx_to_rojo"
path = "src/lib.rs"

[[bin]]
name = "rbxlx-to-rojo"
path = "src/cli.rs"

[dependencies]
env_logger = "0.6"
lazy_static = "1.4"
log = "0.4"
rbx_binary = { git = "https://github.com/rojo-rbx/rbx-dom/", branch = "master" }
rbx_dom_weak = { git = "https://github.com/rojo-rbx/rbx-dom/", branch = "master" }
rbx_reflection = "3"                                                               # TODO: This won't always be latest, and that's an issue
rbx_xml = { git = "https://github.com/rojo-rbx/rbx-dom/", branch = "master" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# CLI
rfd = { version = "0.14.0" }

[dev-dependencies]
pretty_assertions = "0.6"
